DesignPatterns.Composite.GraphicObject.Program();
/*DesignPatterns.Bridge.Rendering.Print();*/
/*DesignPatterns.Adapter.DIAdapter.Program.Exe();*/
/*DesignPatterns.Adapter.Exe.Exec();*/
/*DesignPatterns.Adapter.Execution.Exe();*/
/*DesignPatterns.Prototype.SerialisationCopying.Exe();*/
/*DesignPatterns.Prototype.InterfaceCopying.Exe();*/
/*DesignPatterns.Factories.HotDrinks.Exe();*/
/*DesignPatterns.Factories.Inner.Exe();
DesignPatterns.Factories.Abstract.Exe();*/
/*DesignPatterns.Builder.Faceted.Execution.Exe();*/